Testing pet list scenario
josdem/playwright-vetlog pull request #41
Opened 2024-11-13 03:56 UTC by samuks123

#33

2024-11-13 15:01 UTC, josdem requested changes

2024-11-13 15:01 UTC, josdem commented on tests/e2e/pet.list.spec.ts
> +
Please notice that when you are trying to list all pets in this test, there are no pets registered, therefore the test will fail. I suggest to add this test between `"should registrer a pet"` and `"should delete a pet"`, please take a look at: [pet.registration.spec.ts](https://github.com/josdem/playwright-vetlog/blob/main/tests/e2e/pet.registration.spec.ts)

2024-11-13 18:06 UTC, ahmedhalac approved these changes

2024-11-16 15:26 UTC, josdem commented
Closing this PR in favor of this PR https://github.com/josdem/playwright-vetlog/pull/42 , so that we can incorporate required changes.

2024-11-16 15:26 UTC, closed without merging